@isTest
private inherited sharing class CalloutRecipes_Tests {
    public static String goodUntypedJSON =
        '{\n' +
        ' "Id": "123456", \n' +
        ' "Name": "Universal Containers",\n' +
        ' "Website": "www.universalcontainers.com",\n' +
        ' "Contacts": [ \n' +
        ' { \n' +
        ' "FirstName": "Samantha",\n' +
        ' "LastName": "Smith",\n' +
        ' "Email": "ssmith@example.com"\n' +
        ' },' +
        ' {' +
        ' "FirstName": "James",\n' +
        ' "LastName": "Roberts",\n' +
        ' "Email": "jroberts@example.com"\n' +
        ' }\n' +
        ']\n' +
        '}';

    @isTest
    static void testRawCalloutPositive() {
        // Test code goes here
    }

    @IsTest
    static void testRawCalloutNegative() {
        // Test code goes here
    }

    @isTest
    static void httpGetCalloutToSecondSalesforceOrgPositive() {
        // Test code goes here
    }

    @isTest
    static void httpGetCalloutToSecondSalesforceOrgNegative() {
        // Test code goes here
    }

    @isTest
    static void httpDeleteCalloutToSecondSalesforceOrgPositive() {
        // Test code goes here
    }

    @isTest
    static void httpDeleteCalloutToSecondSalesforceOrgNegative() {
        // Test code goes here
    }

    @isTest
    static void httpPostCalloutToSecondSalesforceOrgPositive() {
        // Test code goes here
    }

    @isTest
    static void httpPostCalloutToSecondSalesforceOrgNegative() {
        // Test code goes here
    }

    @isTest
    static void httpPutCalloutToSecondSalesforceOrgPositive() {
        // Test code goes here
    }

    @isTest
    static void httpPutCalloutToSecondSalesforceOrgNegative() {
        // Test code goes here
    }

    @isTest
    static void httpPatchCalloutToSecondSalesforceOrgPositive() {
        // Test code goes here
    }

    @isTest
    static void httpPatchCalloutToSecondSalesforceOrgNegative() {
        // Test code goes here
    }

    @isTest
    static void calloutWithUntypedResponsePositive() {
        // Test code goes here
    }

    @isTest
    static void insertAccountAndContactsFromUntypedResponsePositive() {
        // Test code goes here
    }
}