<?xml version="1.0" encoding="UTF-8" ?>
<ApexClass xmlns="http://soap.sforce.com/2006/04/metadata">
  <apiVersion>59.0</apiVersion>
  <status>Active</status>
  <testMethods>
    <fullName>CustomRestEndpointRecipes_Tests.testGetMethod</fullName>
    <runTest>true</runTest>
  </testMethods>
  <testMethods>
    <fullName>CustomRestEndpointRecipes_Tests.testPostMethod</fullName>
    <runTest>true</runTest>
  </testMethods>
</ApexClass>