<?xml version="1.0" encoding="UTF-8" ?>
<ApexClass xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>59.0</apiVersion>
    <status>Active</status>
    <testMethods>
        <name>testIsEmpty</name>
        <isParallel>false</isParallel>
    </testMethods>
    <testMethods>
        <name>testContains</name>
        <isParallel>false</isParallel>
    </testMethods>
    <testMethods>
        <name>testAddAllToList</name>
        <isParallel>false</isParallel>
    </testMethods>
</ApexClass>