<?xml version="1.0" encoding="UTF-8" ?>
<ApexClass xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>47.0</apiVersion>
    <status>Active</status>

	<!-- Start of unit tests -->
	<testMethods>
		<name>testGetRequest</name>
		<isParallel>false</isParallel>
	</testMethods>

	<testMethods>
		<name>testPostRequest</name>
		<isParallel>false</isParallel>
	</testMethods>
	<!-- End of unit tests -->
</ApexClass>