<?xml version="1.0" encoding="UTF-8" ?>
<ApexClass xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>51.0</apiVersion>
    <status>Active</status>
    <testMethods>
        <name>testMethod1</name>
        <isParallel>false</isParallel>
        <callout>false</callout>
    </testMethods>
    <testMethods>
        <name>testMethod2</name>
        <isParallel>false</isParallel>
        <callout>false</callout>
    </testMethods>
</ApexClass>